version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: gsLab123!
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./doc:/var/lib/mysql